<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Dashboard.aspx.cs" Inherits="PLNLite.Views.Administrator.Dashboard" %>

<%@ Import Namespace="PLNLite.Frameworks.Security" %>
<%@ Import Namespace="PLNLite.Presentation.Components" %>
<%@ Import Namespace="PLNLite.Business.Components" %>

<!DOCTYPE html>
<script runat="server">
    protected void Page_Load(object sender, EventArgs e)
    {
        //SessionCreator();
        if (Session["username"] == null && Session["password"] == null) Response.Redirect("../../Views/Application/PageSignIn.aspx");
        
        if (!IsPostBack)
        {
            
        }
    }

    protected void SessionCreator()
    {
        Session["username"] = "K495";
        Session["name"] = "Allan Prakosa";
        Session["password"] = "BIOFARMA";
        Session["posid"] = "372";
        Session["email"] = "allan.prakosa@biofarma.co.id";
        Session["coctr"] = "64100";
        Session["jobcd"] = "STAF";
    }

    
</script>

<html lang="en">
<head>
    <% Response.Write(BasicScripts.GetMetaScript()); %>
    <title>Dashboard</title>
    <% Response.Write(StyleScripts.GetCoreStyle()); %>
    <% Response.Write(StyleScripts.GetCustomStyle()); %>
    <% Response.Write(StyleScripts.GetTableStyle()); %>
    <% Response.Write(StyleScripts.GetCustomStyle()); %>
</head>

<body>

    <section id="container">

        <!--header start-->
        <%Response.Write(SideBarMenu.TopMenuElement(Session["name"].ToString())); %>
        <!--header end-->

        <!--left side bar start-->
        <%Response.Write(SideBarMenu.LeftSidebarMenuElementAutoGenerated(Session["username"].ToString())); %>
        <!--left side bar end-->

        <!--main content start-->
        <section id="main-content">
            <section class="wrapper">
                <!-- page start-->
                <div class="row">
                    <div class="col-sm-12">
                            <section class="panel" style="background-image:url(../../Images/office.jpg);background-size:cover;height:680px;">
                            <header class="panel-heading">
                                Dashboard
                          <span class="tools pull-right">
                              <%--<a class="fa fa-chevron-down" href="javascript:;"></a>
                              <a class="fa fa-times" href="javascript:;"></a>--%>
                          </span>
                            </header>
                            <form runat="server">
                                <div class="panel-body" align="center">
                                    <% Response.Write(Notification.FadeIn.GetInfo("Welcome! you are login to PLNLite Customer Care Application")); %>
                                    <% Response.Write(Notification.FadeIn.GetInfo("Please contact our technical support at ext. 37406 for help")); %>
                                </div>
                            </form>
                        </section>
                    </div>
                </div>
                <!-- page end-->
            </section>
        </section>
        <!--main content end-->
        <!--right sidebar start-->
        <!--right sidebar end-->
    </section>

    <!-- Placed js at the end of the document so the pages load faster -->
    <% Response.Write(JS.GetCoreScript()); %>
    <% Response.Write(JS.GetCustomFormScript()); %>
    <% Response.Write(JS.GetDynamicTableScript()); %>
    <% Response.Write(JS.GetInitialisationScript()); %>
</body>
</html>
