<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Statistics.aspx.cs" Inherits="PLNLite.Views.Administrator.Statistics" %>

<%@ Import Namespace="PLNLite.Data.DataAccess" %>
<%@ Import Namespace="PLNLite.Frameworks.Validation" %>
<%@ Import Namespace="PLNLite.Frameworks.Security" %>
<%@ Import Namespace="PLNLite.Presentation.Components" %>
<%@ Import Namespace="PLNLite.Frameworks.Converter" %>
<%@ Import Namespace="PLNLite.Entity.Dictionary" %>
<%@ Import Namespace="PLNLite.Business.Activities" %>
<%@ Import Namespace="System.Data" %>

<!DOCTYPE html>
<script runat="server">
    protected void Page_Load(object sender, EventArgs e)
    {
        //SessionCreator();
        if (Session["username"] == null && Session["password"] == null) Response.Redirect("../../Views/Application/PageSignIn.aspx");

        if (!IsPostBack)
        {
            
        }
    }

    protected void SessionCreator()
    {
        Session["username"] = "K495";
        Session["name"] = "Allan Prakosa";
        Session["password"] = "BIOFARMA";
        Session["posid"] = "372";
        Session["email"] = "allan.prakosa@biofarma.co.id";
        Session["coctr"] = "64100";
        Session["jobcd"] = "STAF";
    }

    
</script>
<html lang="en">
<head>
    <% Response.Write(BasicScripts.GetMetaScript()); %>

    <title>Statistics</title>

    <% Response.Write(StyleScripts.GetCoreStyle()); %>
    <% Response.Write(StyleScripts.GetCustomStyle()); %>

    <!--Morris Chart CSS -->
    <link rel="stylesheet" href="../../Scripts/UserPanel/assets/morris-chart/morris.css">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../Scripts/UserPanel/js/ie8/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="../../Scripts/UserPanel/https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="../../Scripts/UserPanel/https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<section id="container" >
<!--header start-->
        <%Response.Write(SideBarMenu.TopMenuElement(Session["name"].ToString())); %>
        <!--header end-->

        <!--left side bar start-->
        <%Response.Write(SideBarMenu.LeftSidebarMenuElementAutoGenerated(Session["username"].ToString())); %>
        <!--left side bar end-->
<!--sidebar end-->
    <!--main content start-->
    <section id="main-content">
        <section class="wrapper">
        <!-- page start-->
        <div class="row">
            <div class="col-sm-12">
                <section class="panel">
                    <header class="panel-heading">
                       Customer Care Statistics
                        <span class="tools pull-right">
                            <a href="../../Scripts/UserPanel/javascript:;" class="fa fa-chevron-down"></a>
                            <a href="../../Scripts/UserPanel/javascript:;" class="fa fa-cog"></a>
                            <a href="../../Scripts/UserPanel/javascript:;" class="fa fa-times"></a>
                         </span>
                    </header>
                    <div class="panel-body">
                        <div id="graph-bar"></div>
                    </div>
                </section>
            </div>
        </div>
            

        <!-- page end-->
        </section>
    </section>
    <!--main content end-->
<!--right sidebar start-->
<!--right sidebar end-->

</section>

<!-- Placed js at the end of the document so the pages load faster -->

<!--Core js-->
<% Response.Write(JS.GetCoreScript()); %>

<!--Morris Chart-->
<script src="../../Scripts/UserPanel/assets/morris-chart/morris.js"></script>
<script src="../../Scripts/UserPanel/assets/morris-chart/raphael-min.js"></script>
<script>
    <% Response.Write(InitJavascript.InitializeMorrisBar(null)); %>
</script>

<% Response.Write(JS.GetInitialisationScript()); %>
</body>
</html>
